version: '3.4'

services:
  raven:
    image: ravendb/ravendb
    ports:
      - 8081:8080
      - 38881:38888
    volumes:
      - raven-data:/opt/RavenDB/Server/RavenData
    environment:
      - RAVEN_ARGS=--Security.UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Logs_Mode=Information
      - RAVEN_ServerUrl=http://0.0.0.0:8080
      - RAVEN_ServerUrl_Tcp=tcp://0.0.0.0:38888
      - RAVEN_PublicServerUrl=http://raven:8080
      - RAVEN_PublicServerUrl_Tcp=tcp://raven:38888
    env_file: ./license.env
  passaro.api:
    image: passaro-imagem
    ports:
      - 8000:80
      - 8001:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=8001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=passaro.api 
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Passaro.API.pfx
    restart: on-failure
    depends_on:
      - raven
    volumes:
      - ${USERPROFILE}/.aspnet/https:/https

volumes:
  raven-data: